# Generated by Django 5.1.2 on 2024-10-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
